trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Test Results'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false